# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Qiang Hao
tagline:          ''
description:      'Life Hacking'
url:              tobeneo.com
baseurl:          /

author:
  name:           'Qiang Hao'
  url:            http://tobeneo.com/about/

paginate:         5

# Custom vars
version:          

github:           https://github.com/Neo-Hao		