# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Qiang Hao
tagline:          ''
description:      'Learning, Design and Technology, University of Georgia'
url:              tobeneo.com
baseurl:          /

author:
  name:           'Qiang Hao'
  url:            http://home.tobeneo.com/about/

paginate:         5

# Custom vars
version:          

github:           https://github.com/Neo-Hao		
  repo:           
